<a href="https://colab.research.google.com/github/parth5757/pyhon_project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Hi Parth

In [1]:
import numpy as np

In [2]:
# myarr = np.array([3,6,32,7], np.int64) # For single use only it print 0, 1 = 3, 6
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0, 1]

6

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1] = 45

In [6]:
myarr

array([[ 3, 45, 32,  7]])

Array creation: Conversion from other python structure

In [7]:
listarray = np.array([[1,2,3], [5,8,5], [0,5,1]])

In [8]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 5, 1]])

In [9]:
listarray.dtype

dtype('int64')

In [10]:
 listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,15,54)

In [20]:
lspace

array([ 1.        ,  1.26415094,  1.52830189,  1.79245283,  2.05660377,
        2.32075472,  2.58490566,  2.8490566 ,  3.11320755,  3.37735849,
        3.64150943,  3.90566038,  4.16981132,  4.43396226,  4.69811321,
        4.96226415,  5.22641509,  5.49056604,  5.75471698,  6.01886792,
        6.28301887,  6.54716981,  6.81132075,  7.0754717 ,  7.33962264,
        7.60377358,  7.86792453,  8.13207547,  8.39622642,  8.66037736,
        8.9245283 ,  9.18867925,  9.45283019,  9.71698113,  9.98113208,
       10.24528302, 10.50943396, 10.77358491, 11.03773585, 11.30188679,
       11.56603774, 11.83018868, 12.09433962, 12.35849057, 12.62264151,
       12.88679245, 13.1509434 , 13.41509434, 13.67924528, 13.94339623,
       14.20754717, 14.47169811, 14.73584906, 15.        ])